name: hometime
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: hometime.digital.creation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#525156'
    - '#221b13'
    - '#b37d3f'
    - '#539093'
    - '#fdb772'
  brandStrength: 1
  lightness: 0.277486597886309
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
