typography_spectrum: 0
color:
  brandColors:
    - '#525156'
    - '#221b13'
    - '#b37d3f'
    - '#539093'
    - '#fdb772'
  brandStrength: 1
  lightness: 0.277486597886309
  saturation: 0.25
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: hometime
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: tower
    id: 03e9e5c5-0508-43e3-a408-87e0c705ca82
    type: content
favicon: null
title: hometime.digital.creation
description: H.D.C
purpose: []
